apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickchat-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "quickchat-backend"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      # FRONTEND
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quickchat-frontend
            port:
              number: 80

      # BACKEND API
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: quickchat-backend
            port:
              number: 5000

      #  SOCKET.IO 
      - path: /socket.io/
        pathType: Prefix
        backend:
          service:
            name: quickchat-backend
            port:
              number: 5000